### ISSUE TITLE
Densify ?

### ISSUE THREAD

**Issue by geaxgx** [PINTO0309/tflite2tensorflow#11]
#### 9. Download URL for .tflite IR  model https://github.com/google/mediapipe/blob/master/mediapipe/modules/pose_detection/pose_detection.tflite

Hi @PINTO0309 !
New mediapipe version 0.8.6 comes with new models for Blazepose (that's a never ending story :-)
The size of the pose detection model (link above) has been significantly reduced (from ~7.5MB to ~3MB) but unfortunately the model is using a layer named Densify that is not implemented in tflite2tensorflow. I guess it is a relatively new layer. When trying to visualize its data in Netron, I get an "Invalid tensor data size" message.
![image](https://user-images.githubusercontent.com/28948232/124556940-33e3c780-de39-11eb-91f8-b627863efbd4.png)

Do you think Densify can be easily implemented in your tools ? Note that it is not something I am eagerly waiting for since I can do without it by using the previous version of the pose detection model.

**Comment by PINTO0309** [comment]
After analyzing the TensorFlow implementation, it seems that I need to implement the following additional steps in the following order. It's going to take some time.

1. https://www.tensorflow.org/api_docs/python/tf/sparse/SparseTensor
2. https://www.tensorflow.org/api_docs/python/tf/sparse/to_dense
3. https://github.com/tensorflow/tensorflow/blob/5d442828288614d57062f77d8af5d5b090b21469/tensorflow/lite/kernels/internal/reference/densify.h#L29-L43
```cpp
template <typename T>
inline void Densify(const TfLiteSparsity* sparsity,
                    const RuntimeShape& input_shape, const T* input_data,
                    const RuntimeShape& output_shape, T* output_data,
                    TfLiteContext* context) {
  const int dims_count = output_shape.DimensionsCount();
  std::vector<int> vector_shape(dims_count);
  for (int i = 0; i < dims_count; i++) {
    vector_shape[i] = output_shape.Dims(i);
  }

  tflite::optimize::sparsity::FormatConverter<T> converter(vector_shape, *sparsity);
  converter.SparseToDense(input_data, output_shape.FlatSize(), output_data, context);
}
```

**Comment by geaxgx** [comment]
Thanks @PINTO0309 ! As I said before, take your time. I can play with the previous version.

I guess Densify allows a smaller size of the model on disk, but probably not in memory :-)

**Comment by MrNeither** [comment]
@geaxgx I get the same problem. Could you please give a link to the previous version of the model, which can be converted with tflite2tensorflow?

**Comment by PINTO0309** [comment]
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/053_BlazePose

**Comment by PINTO0309** [comment]
Fixes: f032b3128b3bf16191e27916eded639a5db3d782

https://github.com/google/mediapipe/blob/master/mediapipe/modules/pose_detection/pose_detection.tflite

tflite2tensorflow v1.11.7
![model_float32 tflite (2)](https://user-images.githubusercontent.com/33194443/134440060-78986b9d-9805-47d6-8e2e-6c4a1c5fc9ec.png)

**Comment by PINTO0309** [comment]
Commited. TFLite Float32/Float16, ONNX, OpenVINO IR, Myriad Blob, TF-TRT, TFJS, CoreML.
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/053_BlazePose/20_densify_pose_detection

**Comment by geaxgx** [comment]
Thanks @PINTO0309 !
