### ISSUE TITLE
Face landmark model: ERROR: conv2d_21 is not in graph

### ISSUE THREAD

**Issue by hylrh2008** [PINTO0309/tflite2tensorflow#20]
Hi i use tflite2tensorflow==1.16.2 on ubuntu 16.04 get this error.
the model is: https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_landmark/face_landmark.tflite
please help me thanks

**Comment by PINTO0309** [comment]
Close because it does not follow the issue template.
