### ISSUE TITLE
Error on converting of face_landmark.tflite

### ISSUE THREAD

**Issue by hovnatan** [PINTO0309/tflite2tensorflow#21]
### Issue Type

Bug, Support

### OS

Mac OS

### OS architecture

x86_64

### Programming Language

Python

### Framework

TensorFlowLite

### Download URL for tflite file

https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_landmark/face_landmark.tflite

### Description

I get `AssertionError: conv2d_21 is not in graph` when running `tflite2tensorflow --model_path face_landmark.tflite --flatc_path ../flatc --schema_path ../schema.fbs --output_pb`

### Relevant Log Output

```shell
AssertionError: conv2d_21 is not in graph
```

**Comment by hovnatan** [comment]
It turned out the output name in the graph was converted to `conv2d_21_1`.

**Comment by PINTO0309** [comment]
Yes. I just fixed it and committed it. Please wait for about 30 minutes for the CI release to finish.
https://github.com/PINTO0309/tflite2tensorflow/releases/tag/v1.16.3

**Comment by hovnatan** [comment]
Thanks!
