### ISSUE TITLE
Error converting pose_detection.tflite [ No such file or directory: './pose_detection.json' ]

### ISSUE THREAD

**Issue by AnindyaSanyalHiperdyneJP** [PINTO0309/tflite2tensorflow#24]
### Issue Type

Support

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

Python

### Framework

TensorFlowLite

### Download URL for tflite file

https://github.com/google/mediapipe/blob/master/mediapipe/modules/pose_detection/pose_detection.tflite

### Description

I want to convert this tflite model file to tensorflow, TF-TRT and also onnx. While trying to convert to tensorflow, I am receiving the following error "No such file or directory: './pose_detection.json'". I tried both docker and os installation. 

### Relevant Log Output

```shell
sh: ../flatc: No such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/tflite2tensorflow", line 6429, in <module>
    main()
  File "/usr/local/bin/tflite2tensorflow", line 5724, in main
    ops, json_tensor_details, op_types, full_json = parse_json(jsonfile_path)
  File "/usr/local/bin/tflite2tensorflow", line 246, in parse_json
    j = json.load(open(jsonfile_path))
FileNotFoundError: [Errno 2] No such file or directory: './pose_detection.json'
```

**Comment by mch0dmin** [comment]
hi @AnindyaSanyalHiperdyneJP ，Can you tell me where to get pose_ detection.json?

**Comment by DataXujing** [comment]
Do you slove this problem, I have the same problem!

**Comment by PINTO0309** [comment]
1. [No json file #33](https://github.com/PINTO0309/tflite2tensorflow/issues/33)
2. [OSError: SavedModel file does not exist at: saved_model/{saved_model.pbtxt|saved_model.pb} #34](https://github.com/PINTO0309/tflite2tensorflow/issues/34)
