### ISSUE TITLE
The shape of the output layer is different from the result of the tensorflow2onnx transformation.

### ISSUE THREAD

**Issue by ichigosyakure** [PINTO0309/tflite2tensorflow#25]
### Issue Type

Bug

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

Python

### Framework

ONNX

### Download URL for tflite file

VertexAI Auto ML classification  TFlite Format model

### Convert Script

●tflite2tensorflow 

docker run -it --rm --gpus all -v `pwd`:/home/user/workdir ghcr.io/pinto0309/tflite2tensorflow:latest

tflite2tensorflow \
--model_path model.tflite \
--flatc_path ../flatc \
--schema_path ../schema.fbs \
--output_pb \
--optimizing_for_openvino_and_myriad \
--rigorous_optimization_for_myriad

tflite2tensorflow \
--model_path model.tflite \
--flatc_path ../flatc \
--schema_path ../schema.fbs \
--output_onnx \
--onnx_opset 13 \
--output_openvino_and_myriad

●tensorflow2onnx
pip install git+https://github.com/onnx/tensorflow-onnx

python -m tf2onnx.convert --opset 13 --tflite  model.tflite --output model.onnx --dequantize

### Description

I'm trying to convert the attached file from tflite to onnx. (Eventually I want to run it in myriad).
In the conversion source tflite, the input to sortmax is [1×8], but in tflite2tensorflow, it is [7×7×8].
If you try tensorflow2tflite, the input to sortmax becomes [1×8] as in tflite.
I think [1×8] is correct because it is an 8-class classification model.

[tflite]
![tflite_netron](https://user-images.githubusercontent.com/98265611/150681352-ee128946-7a87-4053-8a38-03807a869b58.jpg)

[tflite2tensorflow(savedmodel and onnx)]
![tflite2tensorflow_onnx](https://user-images.githubusercontent.com/98265611/150681448-440de333-e819-4397-88d6-c12a438a7f1a.jpg)

[tensorflow2onnx]
![tensorflow2onnx_onnx](https://user-images.githubusercontent.com/98265611/150681480-7ba69f3d-3e14-423f-82a1-a65d8385a565.jpg)

### Relevant Log Output

```shell
None.
```

**Comment by PINTO0309** [comment]
Please attach the tflite. I know that the structure of the tflite model generated by Auto ML is special.

**Comment by ichigosyakure** [comment]
Sorry. I forgot to attach the file.
I will attach it later.

**Comment by ichigosyakure** [comment]
[tflite.zip](https://github.com/PINTO0309/tflite2tensorflow/files/7920656/tflite.zip)

**Comment by ichigosyakure** [comment]
[file.zip](https://github.com/PINTO0309/tflite2tensorflow/files/7920661/file.zip)
Sorry.　I've re-uploaded it.

**Comment by PINTO0309** [comment]
commit: 18b3e8880ddf3be5a9e9b70e3fe581bc981ab7a6

**Comment by PINTO0309** [comment]
![image](https://user-images.githubusercontent.com/33194443/150704480-c24a706a-4b6e-442b-bc60-4fc57f665082.png)

**Comment by PINTO0309** [comment]
Release: https://github.com/PINTO0309/tflite2tensorflow/releases/tag/v1.18.1

**Comment by PINTO0309** [comment]
Please upgrade the package to v1.18.1 and try again.

**Comment by ichigosyakure** [comment]
I've confirmed the fix.
Thank you.
