### ISSUE TITLE
Failling to import converted pb file in tensorflow. 

### ISSUE THREAD

**Issue by soham24** [PINTO0309/tflite2tensorflow#3]
Hello, I have successfully converted tflite file to pb using your script.  
But I am not able to load this in tensorflow.
I am wondering what steps I have missed.
I am attaching pb file with thi sissue.  
[hair_seg.zip](https://github.com/PINTO0309/tflite2tensorflow/files/5987735/hair_seg.zip)

thank you

**Comment by PINTO0309** [comment]
I just ran the following command, and it seems to be converting well. **`saved_model.pb`** is a special format of **`saved_model`** format. **`model_float32.pb`** is a format that can be read by Netron.
```bash
$ tflite2tensorflow \
  --model_path hair_segmentation.tflite \
  --flatc_path ./flatc \
  --schema_path schema.fbs \
  --output_pb True

$ tflite2tensorflow \
  --model_path hair_segmentation.tflite \
  --flatc_path ./flatc \
  --schema_path schema.fbs \
  --output_no_quant_float32_tflite True
```
![Screenshot 2021-02-16 22:51:33](https://user-images.githubusercontent.com/33194443/108071853-8fd7ca80-70a9-11eb-9a13-f642766d384c.png)
![Screenshot 2021-02-16 22:54:22](https://user-images.githubusercontent.com/33194443/108072213-f230cb00-70a9-11eb-8b49-888957a46e98.png)

**Comment by PINTO0309** [comment]
The problem has been resolved. I will consolidate to issue #2 in the link.
