### ISSUE TITLE
CoreML conversions of face_landmark_with_attention.tflite fails

### ISSUE THREAD

**Issue by hovnatan** [PINTO0309/tflite2tensorflow#32]
### Issue Type

Bug

### OS

Mac OS

### OS architecture

aarch64

### Programming Language

Python

### Framework

CoreML

### Download URL for tflite file

https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_landmark/face_landmark_with_attention.tflite

### Convert Script

tflite2tensorflow --model_path face_landmark_with_attention.tflite --flatc_path ../flatc --schema_path ../schema.fbs --output_coreml

### Description

Error's out with `ValueError: axes don't match array`

### Relevant Log Output

```shell
CoreML convertion started
ERROR: axes don't match array
```

**Comment by PINTO0309** [comment]
https://coremltools.readme.io/docs/onnx-conversion
![image](https://user-images.githubusercontent.com/33194443/178975101-40ebce26-4f1c-46dc-bcaa-cd87e10671ec.png)

Apple is not willing to do it.
Therefore, conversion to coreml is not possible.

**Comment by hovnatan** [comment]
Thanks! I really need this to work on iOS. Do you have any recommendations on how to that?
