### ISSUE TITLE
fail to convert [KNIFT]

### ISSUE THREAD

**Issue by ShunsukeNakai** [PINTO0309/tflite2tensorflow#36]
### Issue Type

Bug

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

Python

### Framework

TensorFlow, TensorFlowLite

### Download URL for tflite file

https://github.com/google/mediapipe/blob/master/docs/solutions/models.md#knift

### Convert Script

```
tar="KNIFT"
option="--flatc_path ../flatc --schema_path ../schema.fbs"

./../flatc -t --strict-json --defaults-json -o ./${tar}/ ../schema.fbs -- ${tar}/knift_float.tflite

tflite2tensorflow --model_path ${tar}/knift_float.tflite ${option} --output_pb
```

### Description

I tried to convert mediapipe KNIFT model but it failed due to channel size mismatch between input and filter.
Is there a mistake in my procedure? If no, could you fix the bug?

### Relevant Log Output

```shell
Traceback (most recent call last):
  File "/usr/local/bin/tflite2tensorflow", line 6614, in <module>
    main()
  File "/usr/local/bin/tflite2tensorflow", line 5881, in main
    TFLite_Detection_PostProcess_flg = make_graph(
  File "/usr/local/bin/tflite2tensorflow", line 720, in make_graph
    output_tensor = tf.nn.depthwise_conv2d(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/ops.py", line 1963, in _create_c_op
    raise ValueError(e.message)
ValueError: Dimensions must be equal, but are 1 and 16 for '{{node depthwise}} = DepthwiseConv2dNative[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], explicit_paddings=[], padding="SAME", strides=[1, 1, 1, 1]](rgb_to_grayscale_1, depthwise/filter_in)' with input shapes: [200,32,32,1], [3,3,16,1].
```

**Comment by PINTO0309** [comment]
Your procedure is correct.
(KNIFT is a very special model. https://github.com/PINTO0309/PINTO_model_zoo/tree/main/054_KNIFT) 

First, the model itself is a very old format. Also, tflite2tensorflow has not been motivated to improve its functionality for some time.

Therefore, I propose a more general and stable conversion method than tflite2tensorflow alone.

- .tflite -> .onnx -> .tflite and .pb
  ```bash
  pip install -U tf2onnx

  python -m tf2onnx.convert \
  --opset 11 \
  --tflite knift_float.tflite \
  --dequantize \
  --output knift_float.onnx
  ```
  ```bash
  pip install onnx2tf

  onnx2tf -i knift_float.onnx -otfv1pb -kat rgb_to_grayscale_1
  ```
  ![image](https://github.com/PINTO0309/tflite2tensorflow/assets/33194443/760d418c-f3ee-4142-a253-1a9a825be653)
  ![image](https://github.com/PINTO0309/tflite2tensorflow/assets/33194443/7c36fc4d-d221-4a6f-b617-77a0071612f3)

**Comment by ShunsukeNakai** [comment]
Thank you for your reply.
I can convert KNIFT model using the procedure you proposed.
