### ISSUE TITLE
Objectron 3D tfjs models: chair and cup are not correct

### ISSUE THREAD

**Issue by luannd** [PINTO0309/tflite2tensorflow#5]
#### 11. URL or source code for simple inference testing code
```javascript
let image_tf = tf.browser.fromPixels(inputCanvasElement).asType('float32');  
let image_tf_resized = tf.image.resizeBilinear(image_tf, [224, 224]).expandDims(0).div(255.0);
prediction = model.predict(image_tf_resized);
    
[prediction_keypoints] = prediction[0].arraySync();
[prediction_prob] = prediction[1].arraySync();
```
#### 12. Issue Details
I can convert the tflite models to tfjs but they seem to predict wrong results while testing by tfjs. The 9 points are kind of random and cannot be detected [correctly.] My preprocessing is the same as https://github.com/sfsrd/objectron. Not sure what's wrong in the conversion pipeline.

**Comment by PINTO0309** [comment]
Here are the inference results in tflite, converted by my tool. There doesn't seem to be any particular problem, so if there is a problem with the inference results when converting to tfjs, it may be a bug in tfjsconverter.

https://user-images.githubusercontent.com/33194443/109388909-4874f800-794d-11eb-8760-6c263b913935.mp4

**Comment by PINTO0309** [comment]
This is the model of CUP that I converted.
[saved_model.zip](https://github.com/PINTO0309/tflite2tensorflow/files/6054624/saved_model.zip)

**Comment by PINTO0309** [comment]
Closed due to lack of progress.
