### ISSUE TITLE
The same generated IR gives different results on CPU and MYRIAD

### ISSUE THREAD

**Issue by geaxgx** [PINTO0309/tflite2tensorflow#9]
#### 12. Issue Details

Hi Katsuya,
I would like to have your opinion on the following problem:
 I have used tflite2tensorflow 1.8.0 to convert the new version of mediapipe Blazepose models (mediapipe version 0.8.4). In this new version, now we have 3 pose landmark models (full, lite and heavy) and one common pose detection model. 
Then I try to test my code BlazeposeOpenvino.py with each model first on CPU then on MYRIAD (OAK-D). Everything seems to work great except when I run the heavy model on the MYRIAD.
For instance, below is the outuput of the heavy model running on the CPU (which looks accurate):
![heavy_on_cpu](https://user-images.githubusercontent.com/28948232/118399118-df537580-b65b-11eb-81e2-afe724147369.png)
And below is the output of the same heavy model running on the MYRIADX :
![heavy_on_myriad](https://user-images.githubusercontent.com/28948232/118399156-1b86d600-b65c-11eb-9e40-582685d4930d.png)
We can see the skeleton is kind of distorded. Actually, in many cases, with other images, we don't even have a skeleton drawn because the score given by the model is too low.

Do you have an idea of what the problem is ? The heavy model is much bigger (27Mo for the bin fle) than the other models. It takes about 30s to load on the MyriadX. But I guess the size is still acceptable otherwise I would get some error messages.

In case, you want to reproduce the problem:
```
# Clone my repo
git clone https://github.com/geaxgx/openvino_blazepose.git
cd openvino_blazepose
# Start your tflite2tensorflow docker
./docker_tflite2tensorflow.sh
cd workdir/models
# In my repo, there are only the FP32 IR version of the models, so we need to download the original tflite file 
# and then convert it using tflite2tensorflow. All is done with the following command:
./get_and_convert_heavy.sh
# Exit docker container
exit

# To test with the heavy model running on the CPU :
python BlazeposeOpenvino.py --lm_xml models/pose_landmark_heavy_FP16.xml -i img/yoga.jpg
# To test on the MYRIAD
python BlazeposeOpenvino.py --lm_xml models/pose_landmark_heavy_FP16.xml -i img/yoga.jpg --lm_device MYRIAD 
```

You can test also with the image img/yoga2.jpg  (no skeleton detected).

Thank you.

**Comment by PINTO0309** [comment]
Ahh... It seems that the specification of OpenVINO has changed so that it is now converted using Interpolate-4. :cry: 
```xml
		<layer id="462" name="model_1/model/up_sampling2d/resize/ResizeBilinear_lambda/ResizeBilinear" type="Interpolate" version="opset4">
			<data antialias="false" coordinate_transformation_mode="half_pixel" cube_coeff="-0.75" mode="linear_onnx" nearest_mode="round_prefer_floor" pads_begin="0,0,0,0" pads_end="0,0,0,0" shape_calculation_mode="sizes"/>
```

**Comment by geaxgx** [comment]
ResizeBilinear again, like in this previous issue https://github.com/PINTO0309/tflite2tensorflow/issues/4 ?
Unfortunately using coordinate_transformation_mode="align_corners", I still have the problem.
I will upgrade my version of openvino (currently 2021.2.185) to be consistent with the version used in tflite2tensorflow. The release notes of 2021.3 says, some support of Interpolate was added for myriad.

**Comment by geaxgx** [comment]
No, I get the same behavior with 2021.3.394.

And if I use a older version of tflite2tensorflow which uses an older version of Openvino, it would convert into Interpolate-1, no ?
I still have a old docker image of tflite2tensorflow on my disk. It is six weeks old, I guess it relies on 2021.2.185. I can try with that version.

**Comment by PINTO0309** [comment]
The inference results are very poor even after applying the transformation in the tensorflow-onnx -> openvino flow.

**Comment by PINTO0309** [comment]
I'll take some time to look into it after tomorrow.

**Comment by geaxgx** [comment]
I agree it is strange. Because the other models (lite and full) are also using Interpolate-4 and they work well on Myriad.

**Comment by geaxgx** [comment]
FYI, I have used that older docker image of tflite2tensorflow (1.6.4) to regenerate the IR files. 
Now Interpolate-1 is used:
```
<layer id="450" name="model_1/model/up_sampling2d/resize/ResizeBilinear_lambda/ResizeBilinear" type="Interpolate" version="opset1">
                        <data align_corners="1" antialias="0" axes="2,3" mode="linear" pads_begin="0" pads_end="0"/>
```
But I still get incorrect values on Myriad.

**Comment by PINTO0309** [comment]
Thank you very much. This is very helpful in narrowing down the patterns that need to be verified.

**Comment by PINTO0309** [comment]
I lost track of the nature of the problem.
- FP16
![Screenshot 2021-05-17 19:16:49](https://user-images.githubusercontent.com/33194443/118472999-77c52500-b744-11eb-9615-ab7075e8b456.png)
- FP32
![Screenshot 2021-05-17 19:17:36](https://user-images.githubusercontent.com/33194443/118473102-95928a00-b744-11eb-8b95-a7413393543e.png)

Convert
```
tflite2tensorflow \
--model_path pose_landmark_heavy.tflite \
--flatc_path ../flatc \
--schema_path ../schema.fbs \
--output_pb \
--optimizing_for_openvino_and_myriad

tflite2tensorflow \
--model_path pose_landmark_heavy.tflite \
--flatc_path ../flatc \
--schema_path ../schema.fbs \
--output_no_quant_float32_tflite \
--output_openvino_and_myriad
```

BlazeposeOpenvino.py
```python
            elif len(self.regions) == 1:
                r = self.regions[0]
                frame_nn = mpu.warp_rect_img(r.rect_points, video_frame, self.lm_w, self.lm_h)
                # Transpose hxwx3 -> 1x3xhxw
                # frame_nn = np.transpose(frame_nn, (2,0,1))[None,]
                frame_nn = np.transpose(frame_nn, (2,0,1))[None,] / 255.0
```
Run inference
```
# FP16
python3 BlazeposeOpenvino.py --lm_xml openvino/FP16/pose_landmark_heavy_FP16.xml -i img/yoga.jpg

# FP32
python3 BlazeposeOpenvino.py --lm_xml openvino/FP32/pose_landmark_heavy_FP32.xml -i img/yoga.jpg
```

**Comment by geaxgx** [comment]
Yes, it works on CPU. But the problem is on MyriadX (I am using the MyriadX of an OAK-D). If you have a NCS2 or an OAK-D, you can try:
python3 BlazeposeOpenvino.py --lm_xml openvino/FP16/pose_landmark_heavy_FP16.xml -i img/yoga.jpg --lm_device MYRIAD

Maybe it is a pure problem Openvino. I wanted to have your opinion before I open an issue with Intel support.

**Comment by PINTO0309** [comment]
Okay, I see. I'll take a look at NCS2.

**Comment by PINTO0309** [comment]
Hmmm... NCS2's processing has always been buggy and sometimes doesn't work properly. I encountered a similar problem when I was verifying YoloV3-tiny at its fastest.
![Screenshot 2021-05-17 20:28:36](https://user-images.githubusercontent.com/33194443/118481531-8ca6b600-b74e-11eb-99ab-75864cea1cf6.png)

**Comment by PINTO0309** [comment]
Huh? It seems to be very different from your result. It's strange. How can there be such a big difference between the way normalization is done inside the model and the way it is done in the outer Python logic?

**Comment by geaxgx** [comment]
You managed to get a better looking skeleton than mine. I was using tflite2tensorflow 1.8. I see there is a version 1.8.1 now. Could it explain the difference ?

**Comment by geaxgx** [comment]
Can you try also with img/yoga2.jpg please ? For me, I don't get any skeleton (score too low).

**Comment by PINTO0309** [comment]
1. Fixed **`FULLY_CONNECTED (MATMUL)`**  bug.
2. Support for quantization of multiple data input models

I don't think this is a relevant fix for this model. Rather, it seems that passing or not passing std =[255.0, 255.0, 255.0] to the optimizer makes a bigger difference.

**Comment by PINTO0309** [comment]
![Screenshot 2021-05-17 20:43:45](https://user-images.githubusercontent.com/33194443/118483099-98937780-b750-11eb-9504-3148c42d7344.png)

**Comment by geaxgx** [comment]
Definitely better than no skeleton ! Strange how the face keypoints are shifted in the hair.

**Comment by PINTO0309** [comment]
Maybe there is a misalignment in the scale conversion process during the processing.

**Comment by PINTO0309** [comment]
I misremembered to use your .sh and ended up running the optimizer conversion command myself. Therefore, the following parameters were converted without specification.
```
${arg_scale_values}
```

**Comment by geaxgx** [comment]
Ah ah I see :-)) It is a good "misremembering" since it allows us to pinpoint the difference in behavior.

Yet I don't understand why the other models (lite and full) are working well on MYARIAD.
Below : python BlazeposeOpenvino.py --lm_xml models/pose_landmark_full_FP16.xml -i img/yoga2.jpg --lm_device MYRIAD
![image](https://user-images.githubusercontent.com/28948232/118485293-885fa600-b718-11eb-85c7-f46aeb2a93c9.png)

**Comment by PINTO0309** [comment]
The model on the left is the one you converted, and the one on the right is the one I converted. There is a big difference in the value of the first Convolution weight. It is probably divided by std=255.0.
![Screenshot 2021-05-17 21:13:49](https://user-images.githubusercontent.com/33194443/118486664-d4c8d700-b754-11eb-87f9-16025e8df876.png)

```
0.03704833984375 / 255 = 0.000145288
```
but, It seems that the first weight number in your transformed model is not simply a number divided by 255. What I am trying to tell you is that there seems to be a bug in the optimizer's division. I have no idea why the lite model works so well...
```
0.00012266870180610567
```
Now notice that the weights of the lite model you transformed hold an order of magnitude more weight than the heavy model, and are expected to be less affected by calculation errors, overflows, or ignored numbers.
```
-0.0012475107796490192
```
![Screenshot 2021-05-17 21:21:32](https://user-images.githubusercontent.com/33194443/118487626-e199fa80-b755-11eb-82b3-e0b714687e4a.png)
However, all of this is just my prediction.

**Comment by PINTO0309** [comment]
This is just a guess on my part, but I think that the accuracy would be higher if the model optimizer were not given mean and std, but instead calculated in the Python logic.

**Comment by geaxgx** [comment]
Thanks for your advice. I am currently busy but later on I will try your suggestion.

**Comment by geaxgx** [comment]
So I have tried your suggestion of doing the scaling (and also the switching BGR -> RGB) in the python code. I confirm the skeleton looks better this way. Unfortunately it is not good enough to be reliablly used. The difference between what I get on CPU and what I get  on Myriad can vary a lot. For instance, when I try with a webcam pointing to my face, the face landmarks are way off the correct position. Also in addition to the landmarks, the model can also output a kind of segmentation mask around the body (it can be visualized by pressing the "s" key).

Below is what I get when run on the CPU:
![heavy_cpu_python_scaling](https://user-images.githubusercontent.com/28948232/118521400-4ac04480-b73b-11eb-863e-5c9d8cf065ba.png)

And now on the Myriad:
![heavy_myriad_python_scaling](https://user-images.githubusercontent.com/28948232/118521459-5ad82400-b73b-11eb-9a8b-403d8d65f416.png)

We can see that the segmentation mask in the latter case is kind of garbage.

**Comment by PINTO0309** [comment]
I have been advised by an Intel engineer. He said that when I infer FP16 on the CPU, it is automatically mapped to FP32 internally. I've been thinking a lot about it since then, and I think the reason why the results are so bad only when FP16 is run in Myriad is that the model handles numbers that are too small or too large for the arithmetic precision of Float16.

**Comment by geaxgx** [comment]
Ah it could be a good explanation. In that case, there is not much hope I guess.

**Comment by geaxgx** [comment]
Just tried on internal GPU:
![image](https://user-images.githubusercontent.com/28948232/118524048-07b3a080-b73e-11eb-8b04-08953be330cf.png)

Garbage too ! It confirms ypur explanation.

**Comment by PINTO0309** [comment]
I'm almost certain of it. :disappointed:

**Comment by PINTO0309** [comment]
Although the tflite file from which the conversion was made is a float16 model, the figure shows that it can be reasoned well because it internally simulates a float32 model.
![Screenshot 2021-05-18 01:37:11](https://user-images.githubusercontent.com/33194443/118524890-985ba200-b779-11eb-8316-34f27cbeb895.png)

**Comment by geaxgx** [comment]
The picture above was with the FP16 model.
And now with the FP32 model on the internal GPU:
![image](https://user-images.githubusercontent.com/28948232/118524960-fd45d680-b73e-11eb-922d-5762817abcc9.png)

**Comment by PINTO0309** [comment]
Hmm. I wonder what the internal implementation is.

**Comment by geaxgx** [comment]
Ha ha I was about to close the issue. But do you still have hope to find a solution ? :-)

**Comment by PINTO0309** [comment]
No. Unfortunately, the situation is hopeless. :crying_cat_face: 
I'll give up gracefully this time.

**Comment by geaxgx** [comment]
This time was not 100% success but yet it was insightful for me.
Thanks again for your great help Katsuya ! I appreciate a lot !

**Comment by geaxgx** [comment]
Hi @PINTO0309 !
I was doing once again the conversion of the tflite to IR openvino when I realized what was going on there : https://github.com/PINTO0309/tflite2tensorflow/issues/9#issuecomment-842280712
The mismatch of `0.03704833984375 / 255 = 0.000145288` and `0.00012266870180610567` is not a bug in the optimizer's division. The problem is just that I was using the `--reverse_input_channels` flag in the optimizer command line. So the weights corresponding to R and B are also reversed for the convolution operation. We can actually found the  0.000145288 value a few lines later in your screencopy :-)

BTW I have a question: in the models you share in your model zoo https://github.com/PINTO0309/PINTO_model_zoo/tree/main/053_BlazePose/10_lite_full_heavy_version_May6_2021 , 
`coordinate_transformation_mode="half_pixel"`
has already been replaced by:
`coordinate_transformation_mode="align_corners"`
Is this fix a modification you are doing manually ?

**Comment by PINTO0309** [comment]
@geaxgx 
I see! It made sense to me that there was a discrepancy in the weights. I've always been one to not specify --reverse_input_channels.

> Is this fix a modification you are doing manually ?

Yes. I've revised and re-committed it while discussing with you. Since the .xml is separated from the weights (.bin), it can be reused as long as the structure of the model is not changed significantly, so I preemptively addressed the issue before you guys raised it.
